### ISSUE TITLE
ginkgo tests EPIC

### ISSUE THREAD

**Issue by Luap99** [containers/podman#18540]
- [ ] machine test should run in parallel
- [ ] bindings should run in parallel
- [ ] do not use os.Exit() as error handling, let ginkgo handle errors so it can provide useful output
- [ ] add test description for the matchers: `Expect(...).To(..., "Description here")`, this is common in the system tests. It will provide a lot more context for someone who looks at these errors.
- [ ] add linter or similar check to make sure tests use GinkgoWriter interface instead of writing to stdout/err directly

e2e tests:
- [ ] check stderr for errors in cleanup (#18442)
- [ ] do not use ExitWithError(), check for actual error messages (#18188)
- [ ] remove flake attempts (#17967)
- [ ] remove code duplication: BeforeEach/AfterEach blocks are duplicated in each file.
- [ ] remove test helpers that do not provide good error messages, i.e. GrepString/LineInOutputStartsWith/etc...
- [ ] cleanup common/setup code: there is a lot of dead and duplicated code there. We should simplify that.
- [ ] check if we can speed up slow tests, some tests run 5 seconds or more. At the bottom of the integration
tests logs you have the timings of all tests. Check if there are any than can be speed up.
- [ ] remove unnecessary images from the test/initial setup, some of them are not required and can be replaced with other images. Less images means less pulls -> faster tests and less flakes

These are issues or general possible improvements I noticed while working on the ginkgo v2 migration. If you have some spare time feel free to tackle some points.

The error messages are properly to much work to change for existing tests but we definitely should require this for new tests on PR review. Running machine/bindings tests in parallel may be useful to safe some CI time/cost.

cc @containers/podman-maintainers @edsantiago

**Comment by Luap99** [comment]
Yeah I don't expect this to be fixed soon, I just wanted to write that down somewhere as I think these things are important. Just properly not important enough to get prioritized.

**Comment by prabhat-kumar96** [comment]
Hi @Luap99,

I would like to help with the item:
> do not use os.Exit() as error handling; let ginkgo handle errors so it can provide useful output

I noticed a few remaining `os.Exit(1)` calls in `test/e2e/` (such as `top_test.go` and `trust_test.go`) and would like to replace them with Ginkgo `Fail()` / `Expect()` assertions so failures produce proper Ginkgo reports.

May I work on a PR for this sub-task?

**Comment by prabhat-kumar96** [comment]
\assign
